{
 "title": "Keycloak Metrics - EKS Monitoring Stack",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Keycloak Health & Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "gauge",
   "description": "Tracks post-GC heap utilization to detect memory pressure before it impacts performance.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_usage_after_gc{area=\"heap\", pool=\"long-lived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak CPU Usage ",
   "type": "gauge",
   "description": "Reports current CPU usage of the Keycloak process within the pod.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keycloak Availability",
   "type": "stat",
   "description": "Monitors the scrape status of Keycloak’s /metrics endpoint. A value of 1 indicates Prometheus can successfully scrape metrics; 0 signals downtime or exporter failure.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"keycloak-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Keycloak - Login Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Failed Login Attempts (By Realm)",
   "type": "timeseries",
   "description": "Tracks the rate of failed login attempts by realm.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (realm) (\n  rate(keycloak_failed_login_attempts_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Logins (By Realm)",
   "type": "timeseries",
   "description": "Tracks the rate of successful logins by realm. \nUseful for identifying usage patterns across environments.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (realm) (\n  rate(keycloak_logins_total[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak - Request Duration Quantiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Keycloak p50 Request Duration",
   "type": "timeseries",
   "description": "50th percentile - Captures the median request duration. \nRepresents typical user experience under normal conditions.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(keycloak_request_duration_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak p95 Request Duration",
   "type": "timeseries",
   "description": "95th percentile - Captures slower requests experienced by ~5% of users. Indicates upper-end latency during load or spikes.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(keycloak_request_duration_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak p99 Request Duration",
   "type": "timeseries",
   "description": "99th percentile - Captures the slowest 1% of requests.\nUseful for identifying rare performance outliers and system bottlenecks.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(keycloak_request_duration_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Level Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}