controller:
  ingressClass: nginx
  ingressClassResource:
    enabled: true
    default: true
  replicaCount: 1
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp # Traffic coming back is raw TCP
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https" # Allow 443 on aws

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator


