nodeExporter:
  enabled: true

prometheus:
  prometheusSpec:
    externalUrl: "" # Will be dynamically set via --set in helm command
    routePrefix: /

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts: [] # Will be dynamically set via --set in helm command
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts: [] # Will be dynamically set via --set in helm command
        secretName: prom-tls

grafana:
  adminUser: "admin"
  adminPassword: "admin"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts: [] # Will be dynamically set via --set in helm command
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts: [] # Will be dynamically set via --set in helm command
        secretName: grafana-tls



